from countryinfo import CountryInfo
name=input("Enter country name of which u want the information: ")
country=CountryInfo(name)
data1=country.alt_spellings()
print(data1)
data2=country.capital()
print(data2)
data3=country.currencies()
print(data3)
data4=country.flag()
print(data4)
data5=country.languages()
print(data5)
# data6=country.all()
# print(data6)
data6=country.timezones()
print(data6)
data7=country.area()
print(data7)
data8=country.wiki()
print(data8)
data9=country.calling_codes()
print(data9)
data10=country.population()
print(data10)
data11=country.borders()
print(data11)
data12=country.info()
# print(data12)
for x,y in data12.items():
    print(f'{x}-->>{y}')

