import turtle
from turtle import *
color('red')
begin_fill()
pensize(5)
setposition(0,0)
left(50)
forward(133)
circle(50,200)
right(140)
circle(50,200)
forward(133)
end_fill()
penup()
setposition(0,220)
pendown()
#pencolor("red")
write("Thanks from Anju Mera Bhaiyu",font = ("Arial",25,"normal"),align="center")
hideturtle()
turtle.done()

