import turtle
from turtle import *
penup()
pencolor('Red')
setposition(-100,250)
pendown()
write('SHAPES',font=('Arial',40,'normal'))
#Square
color('black')
penup()
setposition(0,0)
pensize(3)
pendown()
begin_fill()
forward(150)
left(90) # pointer face upward
forward(150)
left(90)
forward(150)
left(90)
forward(150)
end_fill()
penup()
setposition(0,200)
pendown()
write("I am square",font=("Arial",25,"normal"))
penup()
#rectangle
setposition(-150,80)
pendown()
color('blue')
begin_fill()
pensize(3)
pencolor('blue')
forward(150)
left(90)
forward(75)
left(90)
forward(150)
left(90)
forward(75)
end_fill()
penup()
setposition(-220,120)
write("I am rectangle",font=('Arial',25,'normal'))
#triangle
penup()
color('green')
pencolor('green')
setposition(200,-100)
begin_fill()
pendown()
right(300)
forward(100)
backward(100)
left(-300)
forward(100)
right(300)
backward(100)
end_fill()
penup()
setposition(100,-70)
pendown()
write("I am triangle",font=('Arial',25,'normal'))
#circle
penup()
setposition(-250,-170)
pencolor('brown')
pendown()
begin_fill()
color('brown')
circle(50,360)
end_fill()
penup()
setposition(-330,-30)
pendown()
write("I am circle",font=('Arial',25,'normal'))
#right(90) pointer face downward


'''
#cuboid
color('orange')
penup()
setposition(-98,-98)
pendown()
begin_fill()
right(90)
forward(90)
backward(90)
right(90)
forward(90)
left(90)
forward(90)
left(90)
forward(90)
penup()'''

pendown()
end_fill()

#shape(circle(4))
turtle.done()